name: dollan
description: Aplikasi marketplace untuk wisata.

version: 1.0.5+52

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  scoped_model: 1.0.1
  carousel_slider: ^1.3.0
  cached_network_image: ^1.1.1
  google_maps_flutter: ^0.5.15+1
  location: ^2.3.5
  firebase_core: 0.4.0+6
  flutter_rating_bar: ^1.3.0+1
  url_launcher: ^5.1.2
  datetime_picker_formfield: ^0.2.0
  font_awesome_flutter: ^8.5.0
  flutter_counter: ^1.0.3
  easy_dialog: ^1.0.5
  # firebase_analytics: ^5.0.0
  firebase_auth: ^0.14.0+4
  google_sign_in: ^4.0.4
  firebase_database: 3.0.4
  flutter_facebook_login: ^2.0.1
  shared_preferences: ^0.5.3+4
  flutter_html: ^0.10.4
  webview_flutter: ^0.3.13
  flutter_launcher_icons: ^0.7.2+1
  intl: ^0.15.0
  permission_handler: ^3.2.1+1
  image_picker: 0.6.0+17
  package_info: ^0.4.0+4
#  flutter_downloader: ^1.2.1
  path_provider: ^1.2.0
  share: ^0.6.2+1
  firebase_messaging: ^5.1.6
  cloud_firestore: ^0.12.9+4
  # flutter_range_slider: ^1.4.0
  auto_size_text: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon_dollan.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
   - assets/images/
   - assets/images/popular/
   - assets/icons/
   - assets/icons/new/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Airbnb
      fonts:
        - asset: fonts/airbnb/AirbnbCerealBook.ttf
        - asset: fonts/airbnb/AirbnbCerealMedium.ttf
        - asset: fonts/airbnb/AirbnbCerealLight.ttf
        - asset: fonts/airbnb/AirbnbCerealBold.ttf
        - asset: fonts/airbnb/AirbnbCerealBlack.ttf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
